
###################  项目启动端口  ###################

server:
  port: 80
  context-path: /
  jsp-servlet:
    init-parameters:
      development: true
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding: true
    force: true
    charset: UTF-8
# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.fhs.system.bean;com.fhs.ucenter.bean;com.fhs.fileService.bean;com.fhs.pubservice.bean;com.xhb.park.bean;com.xhb.pay.bean;com.xhb.business.bean;com.xhb.staff.bean;com.xhb.staff.vo;com.xhb.report.bean;com.xhb.wx.bean;com.fhs.file.bean;

fhs:
  autoware:
    package: com.fhs.*;com.fhs.*.*;com.xhb.*;com.xhb.*.*
  login:
    enable-cas: false
    url: /b/page/login
  mybatis-jpa:
    entity-package: com.fhs.**.bean;com.xhb.**.bean;
    mapper-package: com.fhs.**.dao;com.xhb.**.dao;
  safe:
    enable-xss: true
  session:
    timeout: -1
  task:
    default-lock-Minutes: 10
    pool-size: 10
  transcatoin:
    contains: service
    not-contains: api;action;dao
    package: com.fhs;com.xhb
  disable-apollo: true
spring:
  http:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  session:
    store-type: redis
  application:
    name: park_server
  mvc:
    view:
      prefix: /page/
      suffix: .jsp
  rabbitmq:
    host: 36.99.43.54
    password: root_xhb
    port: 5672
    username: admin
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  redis:
    database: 3
    password: root_xhb
    pool:
      max-active: 100
      max-idle: 10
      max-wait: -1
      min-idle: 10
    host: 36.99.43.54
    port: 6379
    timeout: 6000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    initialSize: 1
    maxActive: 20
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    name: allinone
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: trueserver
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://36.99.43.54:3306/park_server_road?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root_xhb
    validationQuery: select 'x'

swagger:
  basepackage: com.xhb
  service:
    description: 项目api
    developer: fhs developers
    name: 公共接口文档

logging:
  config: classpath:log4j2.xml
  level:
    com.fhs.ucenter.dao: DEBUG
    com.fhs.pagex: DEBUG
    com.fhs.system.dao: DEBUG
    com.xhb.pay.dao: DEBUG
    com.xhb.park.dao: DEBUG
    #    com.xhb.business.dao: DEBUG
    #    com.xhb.report.dao: DEBUG
    com.xhb.road.dao: DEBUG


jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.alibaba
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 300000
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}

JWT:
  token-expiration-day: 30
